### ISSUE TITLE
Planning for Kick-Off

### ISSUE THREAD

**Issue by wesleytodd** [openjs-foundation/pkg-vuln-collab-space#2]
To get the collab space kicked off, we are going to be running a session at OpenJS World 2021.  To get this planned, we would like to do a session sometime early next week.  Our proposed agenda (open for discussion to make sure we cover the most important things):

1. Introductions
2. Quick recap of the scope/proposal
3. Outline plan for the session
4. Assign action items and schedule next meeting

To make sure the most folks who want to participate can attend we thought we would open up a short vote.  All times are PST.

*Monday May 10th*

- 👍 7:00 am
- 👎 11:00 am
- 😄 12:00 pm
- 🚀  1:00 pm

*Tuesday May 10th*

- 👀 7:00 am
- 🎉 8:00 am
- 😕 12:00 pm
- ❤️ 1:00 pm

Vote for as many as you can attend and we will choose the best time (with the added restriction that both @darcyclarke and I can attend as the champions).  We will leave this open until Friday, so get your votes in if you would like to attend.

cc @pkg-vuln-collab-space (looks like this doesn't work yet?)
@naugtur @boneskull @mhdawson @dominykas @ljharb @MarcinHoppe @rginn

**Comment by wesleytodd** [comment]
Ok, looks like 12pm on Tuesday is the most popular. I don't see a vote from @darcyclarke, also I realized I didn't directly mention him but he linked to this issue, so I am assuming that will work.

@rginn & @mhdawson, I don't think I can add to the OpenJs calendar, could one of you add this event?

Everyone else before then: feedback on the proposed agenda?

**Comment by mhdawson** [comment]
@lirantal FYI as you sounded interesting in participating in this as well.

**Comment by wesleytodd** [comment]
I think the consensus is that we will record and upload this.  Additionally, we should plan to pick our recurring time so that it does not conflict with OpenJS and Node project meetings if we can.

**Comment by naugtur** [comment]
This thread says 12PST, the calendar event I see is set to 9PST - which one is correct?

**Comment by mhdawson** [comment]
Sorry my mistake. Will move in the calendar.

**Comment by mhdawson** [comment]
Ok, move to 12 PST, sorry about that.

**Comment by wesleytodd** [comment]
Totally understandable @lirantal! You be safe and we will catch up with you after things calm down.  We are all wishing you and your family the best!

**Comment by mhdawson** [comment]
Uploaded recording here: https://youtu.be/KbGA-_wMtrg

**Comment by lirantal** [comment]
Thanks for recording folks! Finally watched it.

Overall, it seems a lot of the discussion was about "solving the problem" but to me at least it isn't clear that we have stated out what the problem actually is. Perhaps it is worth setting those problem areas as general guidelines?

The rest of the session was about producing a recorded session for OpenJS World.
Aside of the interviews, perhaps it would be helpful to also define those primary goals, and general problem areas we'd like to focus on.

**Comment by naugtur** [comment]
@lirantal very much yes. This is a collab space, not a coding project, so the intention is to figure out the scope of the problem and define it well by getting input from many sources. 
We'll definitely fulfill your expectations around problem scope after a bunch of work 😉

BTW, im kinda out of character here because I don't have a lot of input to figuring out the problem boundary, I'm here to solutionize.

**Comment by mhdawson** [comment]
@lirantal from https://github.com/openjs-foundation/pkg-vuln-collab-space#mission-statement

This is the highest level overview of the problem:

Today maintainers deal with a significant influx of issues, PRs (re. updating dependencies) & broader comms when a new CVE is reported on a popular library in our ecosystem. Many of these are being considered "false positives" from an impact/vulnerability perspective. This level of noise creates distrust in the relationships between security companies/researchers, maintainers, & the collective end-users/consumers.

**Comment by lirantal** [comment]
Ahh yes, let's fix that 🤗
